# Generated by Django 2.2.15 on 2020-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('memo', models.TextField()),
                ('priority', models.CharField(choices=[('danger', 'high'), ('secondary', 'normal'), ('light', 'low')], max_length=50)),
                ('duedate', models.DateField()),
                ('status', models.CharField(choices=[('doing', '未完了'), ('done', '完了')], max_length=50)),
            ],
        ),
    ]
