# Generated by Django 2.2.15 on 2020-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200827_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(verbose_name='締め切り日'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', '高い'), ('warning', 'normal'), ('primary', 'low')], max_length=50, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('doing', '未完了'), ('done', '完了')], max_length=50, verbose_name='状況'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
