# Generated by Django 2.2.15 on 2020-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200827_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', '高い'), ('warning', '普通'), ('primary', '低い')], max_length=50, verbose_name='優先度'),
        ),
    ]
