# Generated by Django 2.2.15 on 2020-08-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200827_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('doing', '未完了'), ('done', '完了')], default='doing', max_length=50, verbose_name='状況'),
        ),
    ]
