# Generated by Django 2.2.15 on 2020-08-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200827_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowtoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('creation_order', '作成された順'), ('due_order', '締め切り順')], default='creation_order', max_length=50, verbose_name='並び順')),
            ],
        ),
    ]
