# Generated by Django 2.2.15 on 2020-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200827_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='howtoorder',
            name='ascending_or_descending',
            field=models.CharField(choices=[('ascending', '昇順'), ('descending', '降順')], default='descending', max_length=50, verbose_name='昇順か降順か'),
        ),
    ]
