# Generated by Django 2.2.15 on 2020-08-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_howtoorder_ascending_or_descending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, default='詳細なし', null=True, verbose_name='詳細'),
        ),
    ]
